class_name Run
extends Node

const BATTLE_SCN := preload("res://scenes/battle.tscn")
const BATTLE_REWARDS_SCN := preload("res://scenes/battle_rewards/battle_rewards.tscn")
const CAMPFIRE_SCN := preload("res://scenes/campfire/campfire.tscn")
#const MAP_SCENE := preload("res://scenes/map/map.tscn")
const SHOP_SCN := preload("res://scenes/shop/shop.tscn")
const TREASURE_SCN := preload("res://scenes/treasure/treasure_room.tscn")

@export var run_startup: RunStartup

@onready var map: Map = $Map

@onready var current_view: Node = $CurrentView
@onready var gold_display: GoldDisplay = %GoldDisplay

@onready var collection_button: CardPileOpener = %CollectionButton
@onready var collection_pile_view: CardPileView = %CollectionPileView

@onready var map_button: Button = %MapButton
@onready var battle_button: Button = %BattleButton
@onready var shop_button: Button = %ShopButton
@onready var treasure_button: Button = %TreasureButton
@onready var rewards_button: Button = %RewardsButton
@onready var campfire_button: Button = %CampfireButton

var account: RunAccount
var player_character: CombatantData
var starting_deck: CardPile
var draftable_cards: CardPile
var deck: Deck

func _ready() -> void:
	if !run_startup:
		return
	
	match run_startup.startup_type:
		RunStartup.StartupType.NEW_RUN:
			player_character = run_startup.player_character.create_instance()
			starting_deck = run_startup.deck.duplicate()
			draftable_cards = run_startup.draftable_cards.duplicate()
			print("run.gd STARTING RUN WITH NEW CHARACTER")
			_start_run()
		RunStartup.StartupType.CONTINUED_RUN:
			print("TO DO: load previous run")

func _start_run() -> void:
	account = RunAccount.new()
	deck = Deck.new()
	deck.card_collection = starting_deck
	GameRecord.account = account
	GameRecord.player_data = player_character
	GameRecord.deck = starting_deck
	GameRecord.draftable_cards = draftable_cards
	
	_connect_signals()
	_init_top_bar()
	map.generate_new_map()
	map.unlock_encounter_column(0)

func _change_view(scene: PackedScene) -> Node:
	if current_view.get_child_count() > 0:
		current_view.get_child(0).queue_free()
	
	get_tree().paused = false
	var new_view := scene.instantiate()
	current_view.add_child(new_view)
	map.hide_map()
	
	return new_view

func _show_map() -> void:
	if current_view.get_child_count() > 0:
		current_view.get_child(0).queue_free()
	
	map.show_map()
	map.unlock_next_rooms()

func _connect_signals() -> void:
	Events.battle_won.connect(_on_battle_won)
	Events.battle_rewards_exited.connect(_show_map)
	Events.campfire_exited.connect(_show_map)
	Events.map_exited.connect(_on_map_exited)
	Events.shop_exited.connect(_show_map)
	Events.treasure_room_exited.connect(_show_map)
	
	battle_button.pressed.connect(_change_view.bind(BATTLE_SCN))
	campfire_button.pressed.connect(_change_view.bind(CAMPFIRE_SCN))
	map_button.pressed.connect(_show_map)
	rewards_button.pressed.connect(_change_view.bind(BATTLE_REWARDS_SCN))
	shop_button.pressed.connect(_change_view.bind(SHOP_SCN))
	treasure_button.pressed.connect(_change_view.bind(TREASURE_SCN))

func _init_top_bar() -> void:
	gold_display.run_account = account
	collection_button.card_pile = deck.card_collection
	collection_pile_view.card_pile = deck.card_collection
	collection_button.pressed.connect(collection_pile_view.show_current_collection_view.bind("Collection"))

func _on_battle_entered(room: Room) -> void:
	var battle_scn: Battle = _change_view(BATTLE_SCN) as Battle
	battle_scn.player_data = player_character
	battle_scn.deck = deck
	battle_scn.battle_data = preload("res://battles/tier_0_thralls.tres")
	battle_scn.start_battle()

func _on_battle_won() -> void:
	var rewards_scn := _change_view(BATTLE_REWARDS_SCN) as BattleRewardsScreen
	rewards_scn.run_account = account
	rewards_scn.player_data = player_character
	
	#TEMPORARY TEST CODE WHERE REWARDS SHOULD BE GENERATED BY BATTLE DATA
	rewards_scn.add_gold_reward(77)
	rewards_scn.add_card_reward()

func _on_map_exited(room: Room) -> void:
	match room.type:
		Room.RoomType.BATTLE:
			_on_battle_entered(room)
		Room.RoomType.TREASURE:
			_change_view(TREASURE_SCN)
		Room.RoomType.REST:
			_change_view(CAMPFIRE_SCN)
		Room.RoomType.SHOP:
			_change_view(SHOP_SCN)
		Room.RoomType.BOSS:
			_on_battle_entered(room)
	
